name: Build
on:
  push:
    branches: [master, build]

jobs:
  tests:
    name: Build docker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Base Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ackerr/ackerr:base
          context: .
          file: ./docker/base.Dockerfile

      - name: Code Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ackerr/ackerr:latest
          context: .
          file: ./docker/code.Dockerfile
